version: '3'
services: 
    annuaire: 
        build: 
            context: ./annuaireFastApi
            dockerfile: Dockerfile
        container_name: annuaireFastApi
        volumes:
            - ./annuaireFastApi:/app
        ports:
            - "8000:8000"
        command: uvicorn main:app --host 0.0.0.0 --port 8000

    repertoire: 
        build: 
            context: ./repertoireStockageFastApi
            dockerfile: Dockerfile
        container_name: repertoireStockageFastApi
        volumes:
            - ./repertoireStockageFastApi:/app
        ports:
            - "8111:8111"
        command: uvicorn main:app --host 0.0.0.0 --port 8111


    website:
        build: 
            context: ./frontend
            dockerfile: Dockerfile
        container_name: frontend
        ports:
            - "3000:3000"        
        volumes: 
            - ./frontend:/frontend
        command: npm start
        
    authentification:
        build:
            context: ./authentification
            dockerfile: Dockerfile
        container_name: node-docker
        ports:
            - "8080:8080"
        command: node index.js

    # appsmith:
    #    image: index.docker.io/appsmith/appsmith-ce
    #    container_name: appsmith
    #    ports:
    #        - "80:80"
    #        - "443:443"
    #    volumes:
    #        - ./stacks:/appsmith-stacks
    #    restart: unless-stopped  

    # phoenix:
    #   # The build parameters for this container.
    #   build:
    #      # Here we define that it should build from the current directory.
    #      context: ./middleware/community
    #      dockerfile: Dockerfile
    #   container_name: phoenix    
    #   ports:
    #      # Mapping the port to make the Phoenix app accessible outside of the container.
    #      - '4000:4000'
    #   command: mix phx.server